-----暂时去除
create external table dwd.fact_item
(
    item_id                  bigint        comment '商品id',
    brand_id                 bigint        comment '品牌',
    cid                      bigint        comment '类目ID',
    seller_id                bigint        comment '商家ID',
    shop_id                  bigint        comment '店铺ID',
    shop_cid                 string        comment '商品所属店铺类目id：可以绑定多个店铺类目',
    shop_freight_template_id bigint        comment '运费模版ID',
    attributes               string        comment '商品类目属性keyId:valueId',
    attr_sale                string        comment '商品销售属性keyId:valueId',
    status                   int           comment '商品状态,1:未发布、2:待审核、3:待上架、4:在售、5:已下架、6:锁定、7:申请解锁、8:平台下架、9:系统下架、10:定时下架、11:下线、20:审核驳回、30:删除 ',
    type                     int           comment '1:普通商品 2:虚拟商品',
    item_name                string        comment '商品名称',
    shelve_time              date          comment '上架时间',
    off_shelve_time          date          comment '下架时间',
    task_shelve_time         date          comment '定时上架时间',
    task_off_shelve_time     date          comment '定时下架时间',
    origin                   string        comment '商品产地',
    weight                   string        comment '商品毛重',
    volume                   string        comment '商品体积',
    length                   string        comment '长',
    width                    string        comment '宽',
    height                   string        comment '高',
    ad                       string        comment '广告词',
    keyword                  string        comment '关键字：每个商品可设置5个关键字，英文逗号分隔',
    remark                   string,
    unit_code                string        comment '单位编码',
    unit_name                string        comment '单位名称',
    quotation_way            string        comment '报价方式  1: 按产品数量报价  2：按产品规格报价',
    create_time              date          comment '创建日期',
    create_user              bigint,
    update_time              date          comment '修改日期',
    update_user              bigint,
    yn                       int           comment '是否有效',
    sign                     string        comment '标记',
    status_change_reason     string        comment '平台方下架或锁定或审核驳回时给出的理由',
    platform                 string        comment '所属平台',
    give_away                int           comment '是否是赠品  1:是  2:否',
    pay_type                 string        comment '支付方式  1.货到付款  2:在线支付',
    sale_channel             string        comment '销售渠道  1:web  2:h5  3:app  4:微信',
    points                   float         comment '积分比例',
    upc                      string        comment '商品通用条码：管理商品_单个商品层面',
    goods_code               string        comment '货号：管理商品_批发层面',
    attr_template_id         bigint        comment '属性模板ID',
    `describe`               string        comment '商品描述',
    ad_url                   string        comment '广告词链接',
    source_item_id           bigint        comment '原商品ID',
    master_item_id           bigint        comment '主商品ID',
    rebate_flag              int           comment '是否设置商品交易扣点0:未设置 1:已设置',
    shop_sales_terr_temp_id  bigint        comment '店铺销售区域模板ID',
    create_zipper_time       string        comment '有效开始时间',
    end_zipper_time          string        comment '有效结束时间'
)
PARTITIONED BY (
  dt string
)
stored as orc
location '/user/hive/warehouse/dwd.db/fact_item'
tblproperties ("orc.compression"="snappy");

set hive.exec.dynamici.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
--初始化商品拉链表
insert overwrite table dwd.fact_item
select
    item_id                 ,
    brand_id                ,
    cid                     ,
    seller_id               ,
    shop_id                 ,
    shop_cid                ,
    shop_freight_template_id,
    attributes              ,
    attr_sale               ,
    status                  ,
    type                    ,
    item_name               ,
    shelve_time             ,
    off_shelve_time         ,
    task_shelve_time        ,
    task_off_shelve_time    ,
    origin                  ,
    weight                  ,
    volume                  ,
    length                  ,
    width                   ,
    height                  ,
    ad                      ,
    keyword                 ,
    remark                  ,
    unit_code               ,
    unit_name               ,
    quotation_way           ,
    create_time             ,
    create_user             ,
    update_time             ,
    update_user             ,
    yn                      ,
    sign                    ,
    status_change_reason    ,
    platform                ,
    give_away               ,
    pay_type                ,
    sale_channel            ,
    points                  ,
    upc                     ,
    goods_code              ,
    attr_template_id        ,
    `describe`              ,
    ad_url                  ,
    source_item_id          ,
    master_item_id          ,
    rebate_flag             ,
    shop_sales_terr_temp_id ,
    case when update_time is not null
             then to_date(update_time) else to_date(create_time)
        end as create_zipper_time,
    '9999-12-31' as end_zipper_time,
    date_format(create_time,'yyyyMMdd')
from
    ods.ods_item


create external table dwd.fact_orders
(
    order_id               bigint  comment '订单编号',
    parent_order_id        bigint  comment '父订单编号',
    order_type             int     comment '订单类型
     * 1 普通订单
     * 2 预售订单
     * 3 线下订单
     * 4 积分订单
     * 5 无价格订单
     * 6 B端采购订单 (手工单-向虚拟店铺购买)
     * 7 B端销售订单 (手工单-向虚拟门店销售)
     * 8 B端采购订单 (正常单-向真实店铺购买)
     * 9 门店手工创建销售订单（暂时作废）
     * 10 客户预下单(定制)',
    status                 int  comment '订单状态 0:系统处理中、1:待付款、2:待配送、3:待收货、4:待评价(已无效由其他字段控制)、5:已完成、6:已取消、7:已关闭、8:已删除、9:订单过期、10:待付尾款、11:未付尾款、12:锁单（冻结）、13:待付定金、14:待审核、15:已审核 、16:已驳回、17:待仓库发货',
    buyer_status           int  comment '买家状态',
    seller_type            int  comment '销售类型 1普通 2定制',
    order_platform         string  comment '所属平台',
    order_source           string  comment '订单的来源
（1）PC商城
（2）H5商城',
    total_money            DOUBLE  comment '订单总金额',
    freight_money          DOUBLE  comment '订单总运费',
    discount_money         DOUBLE  comment '订单优惠总金额',
    cut_money              DOUBLE  comment '分切总金额',
    other_fee              DOUBLE  comment '其他费用',
    round_down             DOUBLE  comment '抹零金额',
    actually_payment_money DOUBLE  comment '应支付的的总金额',
    buyer_id               bigint          comment '买家id',
    buyer_name             string           comment '买家账号',
    buyer_shop_id          bigint           comment '买家店铺ID',
    buyer_shop_name        string           comment '买家店铺名称',
    seller_id              bigint           comment '卖家id',
    seller_name            string           comment '卖家账号',
    shop_id                bigint           comment '店铺ID',
    shop_name              string           comment '店铺名称',
    `option`               string           comment '订单标记',
    paid                   int              comment '支付状态 1：未支付 2：已支付',
    payment_source         string           comment '支付渠道',
    payment_time           string             comment '付款时间',
    refund                 int              comment '是否售后  0未退款退货  1已退款退货',
    `exchange`               int              comment '是否换货  0未换货  1换货',
    invoice                int              comment '是否需要发票 —— 0不需要  1普通发票  2 增值税发票',
    buyer_memo             string           comment '买家备注',
    seller_memo            string           comment '卖家备注',
    is_change_price        int              comment '是否改价  —— 0未改价 1已改价',
    settle_flag            int              comment '结算标识',
    evaluation             string           comment '评价状态(1:无,2:是)',
    create_time            string             comment '创建时间',
    modify_time            string             comment '修改时间',
    create_user            bigint           comment '创建者',
    modify_user            bigint           comment '修改者',
    deposit                DOUBLE   comment '预售定金',
    retainage              DOUBLE   comment '预售尾款',
    retainage_order_id     bigint         comment '尾款支付订单编号',
    presell_id             bigint         comment '预售Id',
    presell_pay_type       int            comment '预售付款类型：0：仅全款，1：仅定金',
    order_credit           int            comment '订单使用积分',
    yn                     int            comment '是否有效： 0无效  1有效
（注：该字段做彻底删除用）',
    manage_user_id         bigint         comment '经销商业务员用户ID(卖方业务员ID)',
    manage_username        string         comment '经销商业务员用户名(卖方业务员名称)',
    buyer_manage_user_id   bigint         comment '买方业务员ID',
    buyer_manage_username  string         comment '买方业务员名称',
    purchase_date          string           comment '采购日期',
    warehouse_code         string         comment '仓库编码(买方入库仓库)',
    warehouse_name         string         comment '仓库名称(买方入库仓库)',
    reason                 string         comment '驳回原因',
    audit_time             string           comment '审核时间',
    audit_user_id          int            comment '审核人ID',
    audit_username         string         comment '审核人用户名',
    remark                 string         comment '备注',
    seller_org_code        string         comment '归属卖家组织机构编码',
    seller_org_parent_code string         comment '归属卖家上级组织机构编码',
    buyer_org_code         string         comment '归属买家组织机构编码',
    buyer_org_parent_code  string         comment '归属买家上级组织机构编码',
    delivery_type          int            comment '配送方式 1：自提 2：汽运',
    print_price            int            comment '是否打印价格： 1，否；2，是',
    consignment            int            comment '发货完成标识：1，否；2，是',
    store_complete         int            comment '入库完成标识：1，否；2，是',
    balance_amount         DOUBLE comment '余额支付金额',
    balance_flag           int            comment '余额支付标识（0，否；1，是）',
    issue_flag             int            comment '订单下发标识 0：未下发 1：已下发 2：下发失败 3:无仓发货（目前只针对c端订单）',
    self_pick_flag         int            comment '1:自提订单 0:非自提订单',
    expect_receive_time    string           comment '期望收货时间',
    delivery_remark        string         comment '发货备注',
    create_zipper_time           string     comment '有效开始时间',
    end_zipper_time           string     comment '有效结束时间'
) COMMENT '订单拉链表'
PARTITIONED BY (
  dt string
)
stored as orc
location '/user/hive/warehouse/dwd.db/fact_orders'
tblproperties ("orc.compression"="snappy");
--动态分区 在spark-sql中执行
set hive.exec.dynamici.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
--初始化拉链表
insert overwrite table dwd.fact_orders
select order_id,
       parent_order_id,
       order_type,
       status,
       buyer_status,
       seller_type,
       order_platform,
       order_source,
       total_money,
       freight_money,
       discount_money,
       cut_money,
       other_fee,
       round_down,
       actually_payment_money,
       buyer_id,
       buyer_name,
       buyer_shop_id,
       buyer_shop_name,
       seller_id,
       seller_name,
       shop_id,
       shop_name,
       `option`,
       paid,
       payment_source,
       payment_time,
       refund,
       `exchange`,
       invoice,
       buyer_memo,
       seller_memo,
       is_change_price,
       settle_flag,
       evaluation,
       create_time,
       modify_time,
       create_user,
       modify_user,
       deposit,
       retainage,
       retainage_order_id,
       presell_id,
       presell_pay_type,
       order_credit,
       yn,
       manage_user_id,
       manage_username,
       buyer_manage_user_id,
       buyer_manage_username,
       purchase_date,
       warehouse_code,
       warehouse_name,
       reason,
       audit_time,
       audit_user_id,
       audit_username,
       remark,
       seller_org_code,
       seller_org_parent_code,
       buyer_org_code,
       buyer_org_parent_code,
       delivery_type,
       print_price,
       consignment,
       store_complete,
       balance_amount,
       balance_flag,
       issue_flag,
       self_pick_flag,
       expect_receive_time,
       delivery_remark,
       case when modify_time is not null
                then to_date(modify_time) else to_date(create_time)
           end as create_zipper_time,
       '9999-12-31' as end_zipper_time,
       date_format(create_time,'yyyyMMdd')
from ods.ods_orders